### ISSUE TITLE
header作成

### ISSUE THREAD

**Issue by naruto1031** [DEJIBUMI-Development-team/HEW_IH12_5#16]

**Comment by duwns5769** [comment]
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <title>でじぶみ</title>
  <link rel="stylesheet" href="./css/main.css">
</head>
<body>  

<header class="navigator">
  <div class="navigator_content">
    <div class="navigator_left">
      <a href="index.html"><img src="image/logo.png" alt="logo"></a>
      <a href="">手紙一覧</a>
      <a href="">ギフト</a>
      <a href="">マイページ</a>
    </div>
    
    <div class="navigator_right">
      <a href="">会員登録</a>
      <a href="">ログイン</a>
    </div>
  </div>
</header>

**Comment by duwns5769** [comment]
作成しました
